<a href="https://colab.research.google.com/github/vg11072001/Python-programming/blob/main/python_practise_hackerrank_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HackerRank Solution

### 1. if-else

In [ ]:
# given
import math
import os
import random
import re
import sys
if __name__ == '__main__':
    n = int(input().strip())

if (n%2 != 0):
  print('weird')
elif (n%2 == 0 and 2<n<5):
  print('weird')
elif (6<n<20):
  print('weird')
else:
  print("not weird")

2
not weird


#### 2. Arithemtic operators

In [ ]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a+b)
    print(a-b)
    print(a*b)

3
2
5
1
6


3. Divsion

In [ ]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a//b)
    print(a/b)


# %   ---> remainder
# /   ---> divider ke upar likhua (without decimal)
# //  ---> divider ke upar likhua (with decimal)= float

4
3
1
1.3333333333333333


4. Loops

In [ ]:
if __name__ == '__main__':
    n = int(input())
    for i in range(n):
        print(i**2)   


  # range(a,b,c) - a = start, b = end, c = gap
  # a**b - b power of a

5
0
1
4
9
16


5. Write a function - with leap year

In [ ]:
def is_leap(year):
    leap = False
    
    # Write your logic here
    if (year%400 ==0):
        leap = True
    elif (year%4 ==0 and year%100 != 0):
        leap = True

    return leap


year = int(input())
print(is_leap(year))


# important 
# % (year%400 ==0)  is not equal to (year%100 ==0 and year%4 ==0)
# division 400 -- then leap
# division 4 and not 100 -- then leap
# division else = not leap

2100
False


6. print fuction

In [ ]:
if __name__ == '__main__':
    n = int(input())
    
    for i in range(1, n+1):
        print(i, end='')
        
# in pypy2 solution is--
n = int(input())
print(''.join(map(str,range(1,n+1))))


# " ".join(content) 
# join can be used for removing spces in btw (from with gap spaces)
# koin can be used for adding spaces  in btw (from without gap text)

# string_name.join(iterable) ----> iterable = list, tuple, string, dictionary

3
123

In [ ]:
# end = ' ' 
# By default python’s print() function ends with a newline
# so we end it with 
# This Python program must be run with
# Python 3 as it won't work with 2.7.

# ends the output with a <space>
print('Red','Green','Blue', sep=',', end='@')
print('geeksforgeeks')

Red,Green,Blue@geeksforgeeks


7. List comprehension

In [ ]:
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    
    print([[i,j,k] for i in range(x+1) for j in range(y+1) for k in range(z+1) if i+j+k !=n])
    
    
    #   wrong bcoz final result all should close on []
    #   for i in range(x+1):
    #     for j in range(y+1):
    #         for k in range(z+1):
    #             if i+j+k != n:
    #                 print([[i,j,k]], end =', ')

2
3
4
5
[[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 0, 3], [0, 0, 4], [0, 1, 0], [0, 1, 1], [0, 1, 2], [0, 1, 3], [0, 2, 0], [0, 2, 1], [0, 2, 2], [0, 2, 4], [0, 3, 0], [0, 3, 1], [0, 3, 3], [0, 3, 4], [1, 0, 0], [1, 0, 1], [1, 0, 2], [1, 0, 3], [1, 1, 0], [1, 1, 1], [1, 1, 2], [1, 1, 4], [1, 2, 0], [1, 2, 1], [1, 2, 3], [1, 2, 4], [1, 3, 0], [1, 3, 2], [1, 3, 3], [1, 3, 4], [2, 0, 0], [2, 0, 1], [2, 0, 2], [2, 0, 4], [2, 1, 0], [2, 1, 1], [2, 1, 3], [2, 1, 4], [2, 2, 0], [2, 2, 2], [2, 2, 3], [2, 2, 4], [2, 3, 1], [2, 3, 2], [2, 3, 3], [2, 3, 4]]


8. Runner Up

In [ ]:
# doubt

9. Nested List

In [ ]:
## again
if __name__ == '__main__':
    students = []
    scores= []
    n = int(input())
    for _ in range(n):
        name = input()
        score = float(input())
        scores.append(score)
        students.append([name,score])
    
    # code
    maxscore= max(scores) 
    y = -9999999
    for i in range(n):
      if students[i][1] < maxscore and students[i][1]>y:
          y = students[i][1]

    for i in range(n):
      if y == students[i][1]:
        print(students[i][0]) 


3
h
10
b
20
c
30
b


10. Percentage

11. Lists

In [ ]:
if __name__ == '__main__':
    N = int(input())
    Output = []
    for i in range(0,N):
        ip = input().split()
        if ip[0] == "print":
            print(Output)
        elif ip[0] == "insert":
            Output.insert(int(ip[1]),int(ip[2]))
        elif ip[0] == "remove":
            Output.remove(int(ip[1]))
        elif ip[0] == "pop":
            Output.pop()
        elif ip[0] == "append":
            Output.append(int(ip[1]))
        elif ip[0] == "sort":
            Output.sort()
        else:
            Output.reverse()

12. Tuples

In [ ]:
#  hash() is one of the functions in the __builtins__ module, so it need not be imported.

n = int(input())
integer_list = tuple(map(int, input().split()))
print(hash(integer_list))

2
1 2
3713081631934410656


13. sWAP cASE

In [ ]:
def swap_case(s):
    n = len(s)
    t = ''
    for i in range(n):
      if s[i].isupper() == True:
        t += s[i].lower()
      elif  s[i].islower() == True:
        t += s[i].upper()
      else:
        t += s[i] 
    return t

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

# to check uppercase and lowercase - we use ISUPPER() AND ISLOWER()
# to convert into uppercase and lowercase - we use UPPER() and LOWER()

Swap Case
sWAP cASE


14. String Split and Join

In [ ]:
def split_and_join(line):
    # write your code here

    line = line.split(" ")
    line = "-".join(line)
    return line
    
if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

# split used 
# syntax: str.split(separator, maxsplit)
# if using sperator means giving the number on whhich we want to divide string to peices.

Don't loose move forward
Don't-loose-move-forward


15. What's your name

In [ ]:
def print_full_name(first, last):
    print ("Hello {} {}! You just delved into python.". format(first, last))

if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

Vanshika
Gupta
Hello Vanshika Gupta! You just delved into python.


16. Mutations 

In [ ]:
def mutate_string(string, position, character):
    l =(list(string))
    l[position]=character
    string =''.join(l)
    return string

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

# string can be can access an index by:

abjdridosmdfv
5 k
abjdrkdosmdfv


In [ ]:
# From 14 and 16
#both followed same approach ---> Split or make it list ----> use join

In [ ]:
# if finding string like 17 
# use then for loop apprach

17. Fnd a string

In [ ]:
def count_substring(string, sub_string):
    count_sub_string = 0
    for i in range(len(string) - len(sub_string) + 1):
    
        if string[i:i + len(sub_string)] == sub_string:
            count_sub_string += 1
    return count_sub_string



if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

ABCDCDC
CDC
2


18. String Validators

In [ ]:
if __name__ == '__main__':
    s = input()
    print(any(a.isalnum() for a in s) )
    print(any(a.isalpha() for a in s) )
    print(any(a.isdigit() for a in s) )
    print(any(a.islower() for a in s) )
    print(any(a.isupper() for a in s) )
 

qA2
True
True
True
True
True


### 19. Text Alignment

In [ ]:
#Replace all ______ with rjust, ljust or center. 

thickness = int(input()) #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

#Top Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

#Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))    

#Bottom Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))    

#Bottom Cone
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))

5
    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
                    HHHHHHHHH 
                     HHHHHHH  
                      HHHHH   
                       HHH    
                        H     


20. Text WRAP

In [ ]:
import textwrap

def wrap(string, max_width):
   for i in range(0, len(string)+1, max_width):
        result = string[ i: i+max_width ]
        if len(result) == max_width:
            print(result)
        else:
            return(result)

if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

ABCDEFGHIJKLMNOPQRSTUVWXYZ
5
ABCDE
FGHIJ
KLMNO
PQRST
UVWXY
Z


21. Designer door mat

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

s = list(map(int, input().split()))

for i in range(1,s[0],2):
     print(str('.|.'*i).center(s[1], '-'))
print('WELCOME'.center(s[1],'-'))

for i in range(s[0]-2,-1,-2):
     print(str('.|.'*i).center(s[1], '-'))

9 27
------------.|.------------
---------.|..|..|.---------
------.|..|..|..|..|.------
---.|..|..|..|..|..|..|.---
----------WELCOME----------
---.|..|..|..|..|..|..|.---
------.|..|..|..|..|.------
---------.|..|..|.---------
------------.|.------------


22. String Formating 

In [ ]:
def print_formatting(number):
  l1 = len(bin(number)[2:])
  for i in range(1, number+1):
     print(str(i).rjust(l1,' '),end=" ")
     print(oct(i)[2:].rjust(l1,' '),end=" ")
     print(((hex(i)[2:]).upper()).rjust(l1,' '),end=" ")
     print(bin(i)[2:].rjust(l1,' '),end=" ")
     print("")

if __name__ == '__main__':
  n = int(input())
  print_formatting(n)

17
    1     1     1     1 
    2     2     2    10 
    3     3     3    11 
    4     4     4   100 
    5     5     5   101 
    6     6     6   110 
    7     7     7   111 
    8    10     8  1000 
    9    11     9  1001 
   10    12     A  1010 
   11    13     B  1011 
   12    14     C  1100 
   13    15     D  1101 
   14    16     E  1110 
   15    17     F  1111 
   16    20    10 10000 
   17    21    11 10001 


23. Alphabet Rangoli

In [ ]:
def print_rangoli(size):
    # your code goes here
    import string
    design = string.ascii_lowercase 
    L=[]
    for i in range(n):
        s = "-".join(design[i:n])
        L.append((s[::-1]+s[1:]).center(4*n-3, "-"))
        
    print('\n'.join(L[:0:-1]+L))
    
    
if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)

5
--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


24. Capitalize

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):

  #code
    for x in s[:].split():
        s = s.replace(x, x.capitalize())
    return s

if __name__ == '__main__':

    s = input()
    resukt = solve(s)
    print(result)


vanshika gupta
Vanshika Gupta


25. itertools.product()

In [ ]:
from itertools import product

a=list(map(int, input().split()))
b=list(map(int, input().split()))
print(' '.join([str(x) for x in list(product(a,b))]))

1 2
3 4
(1, 3) (1, 4) (2, 3) (2, 4)


26. itertools.permuataions()

27. Polar coordinates

### 28. Introductions to sets

In [ ]:
def average(array):
    # your code goes here
    ar = set(array)
    average = float (sum(ar)/len(ar))
    return average 

if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

5
11 12 13 14 15
13.0


29. No Idea!

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n_m = input().split()
n_m = map(int, n_m)
n = map(int, input().split())
MA = set(map(int, input().split()))
MB = set(map(int, input().split()))

count = 0
for i in n:
    if i in MA:
        count = count + 1
    elif i in MB:
        count = count - 1
        
print(count)

3 2
1 5 3
3 1
5 7
1


30. Symmetric Difference

In [ ]:
int(input())
N = input().split()
Nint = set(list(map(int, N)))
int(input())
M = input().split()
Mint = set(list(map(int, M)))
res = []
for i in list(Nint.difference(Mint)):
    res.append(i)
for j in list(Mint.difference(Nint)):
    res.append(j)
for k in sorted(res):
    print( k)


4
2 4 5 9
4 
2 4 11 12
5
9
11
12


31. Set.add()

In [ ]:
#find distinct 
 = int(input())
s = set()
for i in range(n):
    a= input()
    s.add(a)
    
print(len(s))in

3
dia
ny
dia
2


32. Set.discard(), .remove() and . pop()

In [ ]:
n = int(input())
numbers = set()
for x in (input().split(' ')):
  numbers.add(int(x))
for x in range(int(input())):
  cmd = input().split(' ')
  if cmd[0] == 'pop':
    numbers.pop()
  elif cmd[0] == 'remove':
      numbers.remove(int(cmd[1]))
  else:
    numbers.discard(int(cmd[1]))
print (sum(numbers))


4
1 2 3 4
2
pop
remove 2
7


33. Set.union() Operation

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

a = int(input())
eng_numbers = set()
for x in (input().split(' ')):
  eng_numbers.add(int(x))
b = int(input())
fren_numbers = set()
for x in (input().split(' ')):
  fren_numbers.add(int(x))


total = len((eng_numbers.union(fren_numbers)))
print(total)

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
13


34. Set.intersection() Operations

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
a = int(input())
s = set(map(int, input().split()))
b = int(input())
t = set(map(int, input().split()))

print(len(s.intersection(t)))

35. set.difference () Operations

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
a = int(input())
s = set(map(int, input().split()))
b = int(input())
t = set(map(int, input().split()))

print(len(s.difference(t)))


36. set.symmetric_difference() Operation

In [ ]:
a = int(input())
s = set(map(int, input().split()))
b = int(input())
t = set(map(int, input().split()))

print(len(s.symmetric_difference(t)))


37. Set Mutations

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
if __name__ == '__main__':
    (_, A) = (int(input()),set(map(int, input().split())))
    B = int(input())
    for _ in range(B):
        (command, newSet) = (input().split()[0],set(map(int, input().split())))
        getattr(A, command)(newSet)

    print (sum(A))


## my
a = int(input())
s = set(map(int, input().split()))
b = int(input())
for i in range(b):
    t = input().split()
    u = set(map(int, input().split()))
    if t[0] == 'intersection_update':
       s.intersection_update(u)
    if t[0] == 'update':
       s.update(u) 
    if t[0] == 'symmetric_difference_update':
       s.symmetric_difference_update(u)
    if t[0] == 'difference_update':
       s.difference_update(u)

print(sum(s))

38. The Captain's Room

In [2]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
K = int(input())
set_S = set()
sumlist_S = 0
for i in input().split():
    I = int(i)
    set_S.add(I)
    sumlist_S += I

print((sum(set_S)*K - sumlist_S)//(K-1))


# GOOD Approach
# find the Captain's room number.
# The total number of tourists or the total number of groups of families is not known to you.
# You only know the value of  and the room number list.

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2 2 4 1 2 5 1 
4


39. Check Subset

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
x = int(input())
for i in range(x):
    a = int(input())
    s = set(map(int, input().split()))
    b = int(input())
    t = set(map(int, input().split()))
    print(s.issubset(t))
    

40. Check Strict Superset

In [ ]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
s = set(map(int, input().split()))
a = int(input())
count = 0
for i in range(a):
    b = set(map(int, input().split()))
    if (s.issuperset(b)):
        count = count+1
    else:
        count = count-1

if (count==a):
    print ("True")
else: 
    print ("False")


1 2 3 4 5 6
2
1 2 3
100 12 11
False


### 41. Polar Coordinates

In [4]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import cmath
print(*cmath.polar(complex(input())), sep='\n')


1+2j
2.23606797749979
1.1071487177940904


42. Find Angle ABC

In [7]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
# Enter your code here. Read input from STDIN. Print output to STDOUT
import math
a = int(input())
b = int(input())
M = math.sqrt(a**2+b**2)
theta = math.acos(b/M )
print(str(round(math.degrees(theta)))+'°')


# Above one shows error due to ASCII Value doesn't contain
import math
ab=int(input())
bc=int(input())
ca=math.hypot(ab,bc)
mc=ca/2
bca=math.asin(1*ab/ca)
bm=math.sqrt((bc**2+mc**2)-(2*bc*mc*math.cos(bca)))
mbc=math.asin(math.sin(bca)*mc/bm)
print(int(round(math.degrees(mbc),0)),'\u00B0',sep='')

10
10
45°


43. Triangle Quest 2

In [8]:
for i in range(1,int(input())+1): #More than 2 lines will result in 0 score. Do not leave a blank line also
    print(((10**i - 1)//9)**2)

# GREAT TIP
# sometimes maths give good reults, try to think when answers in number that, is maths logic possible?

6
1
121
12321
1234321
123454321
12345654321


44. Mode Divmod

In [10]:
a=int(input())
b = int(input())
c = a/b 
d = a%b
print(c)
print(d)
print(divmod(a,b))


177
10
17.7
7
(17, 7)


45. Power - Mode power

In [14]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
a = int(input())
b = int(input())
c = int(input())

print("Pow of a,b ".format(pow(a,b)))
print("Pow of a,b, c4 ".format(pow(a,b,c)))

3
4
5
Pow of a,b 
Pow of a,b, c 


46. Triangle Quest

In [17]:
for i in range(1, int(input())):
    print(int((10**i/9)*i))    


4
1
22
333


47. Integers Come in all Sizes

In [18]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
a = int(input())
b = int(input())
c = int(input())
d = int(input())

print(pow(a,b)+pow(c,d))

9
29
7
27
4710194409608608369201743232


### 48. Date and Time

In [1]:
import calendar

m, d, y = map(int, input().strip().split())

print(calendar.day_name[calendar.weekday(y, m, d)].upper())


11 05 2001
MONDAY


49.Time delta

In [4]:
import datetime

format_string = "%a %d %b %Y %H:%M:%S %z"
T = int(input())

for test in range(T):
    t1 = str(input())
    t2 = str(input())

    parsed_t1 = datetime.datetime.strptime(t1, format_string)
    parsed_t2 = datetime.datetime.strptime(t2, format_string)

    diff = parsed_t2 - parsed_t1

    print(int(abs(diff.total_seconds())))


2
Sun 10 May 2015 13:54:36  -0700
Sun 10 May 2015 13:54:36  -0000
25200
Sun 02 May 2015 19:54:36  +0530
Fri 01 May 2015 13:54:36 -0000
88200


### 50. Numpy - Arrays

51. Shape and Reshape

In [2]:
import numpy

my_array= numpy.array(list((map(int, input().split()))))
print(numpy.reshape(my_array,(3,3)))


# import numpy as np
# print(np.array(input().split(),int).reshape(3,3))


9 8 7 6 5 4 3 2 1
[[1 2 3]
 [4 5 6]
 [7 8 9]]


52. Transpose and Flatten

In [4]:

import numpy
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]
